const PREFIX='cookiehost_';
const statusBox=document.querySelector('#status'); const frame=document.querySelector('#site-frame'); const wrap=document.querySelector('#site-frame-wrap');
const setStatus=(title,detail,kind='')=>{statusBox.className=`status ${kind}`;statusBox.querySelector('.status-title').textContent=title;statusBox.querySelector('.status-detail').textContent=detail;};
const cookieMap=()=>Object.fromEntries(document.cookie.split('; ').filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i),decodeURIComponent(x.slice(i+1))]}));
const bytesFromBase64=value=>{try{const raw=atob(value);const out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}catch(e){throw new Error('BASE64')}};
async function ungzip(bytes){try{if(!('DecompressionStream' in window))throw 0;const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));return new TextDecoder().decode(await new Response(stream).arrayBuffer())}catch(e){throw new Error('GZIP')}}
const isExternal=url=>/^(?:[a-z]+:|\/\/|#|data:|mailto:)/i.test(url);
const normalize=(base,target)=>{const parts=(base+'/'+target).split('/');const out=[];for(const p of parts){if(!p||p=='.')continue;if(p==='..')out.pop();else out.push(p)}return out.join('/')};
function inlineAssets(html,files,entryPath){const doc=new DOMParser().parseFromString(html,'text/html');const map=new Map(files.map(f=>[f.path,f.content]));const base=entryPath.includes('/')?entryPath.slice(0,entryPath.lastIndexOf('/')):'';
 doc.querySelectorAll('link[rel="stylesheet"][href]').forEach(link=>{const href=link.getAttribute('href');if(isExternal(href))return;const key=normalize(base,href.split(/[?#]/)[0]);if(!map.has(key))return;const style=doc.createElement('style');style.textContent=map.get(key);link.replaceWith(style)});
 doc.querySelectorAll('script[src]').forEach(script=>{const src=script.getAttribute('src');if(isExternal(src))return;const key=normalize(base,src.split(/[?#]/)[0]);if(!map.has(key))return;script.removeAttribute('src');script.textContent=map.get(key).replace(/<\/script/gi,'<\\/script');}); return '<!doctype html>'+doc.documentElement.outerHTML;}
(async()=>{try{const cookies=cookieMap();const count=Number(cookies[`${PREFIX}count`]);if(!count){setStatus('No CookieHost website was found in this browser.','Bake a website first, then open /loadsite.','error');return}setStatus('Step 2 · Collecting chunks…',`Looking for ${count} cookie chunks.`);let encoded='';for(let i=0;i<count;i++){const name=`${PREFIX}${String(i).padStart(4,'0')}`;if(!(name in cookies)){setStatus('CookieHost data is incomplete.',`Missing chunk: ${name}`,'error');return}encoded+=cookies[name]}
 setStatus('Step 3 · Decoding and decompressing…','Unpacking the gzip payload in the browser.');let json;try{json=await ungzip(bytesFromBase64(encoded))}catch(e){setStatus(e.message==='BASE64'?'CookieHost data is corrupted.':'Unable to decompress CookieHost data.','The stored cookie payload could not be opened.','error');return}
 setStatus('Step 4 · Reconstructing HTML…','Resolving local CSS and JavaScript references.');let pack;try{pack=JSON.parse(json);if(!pack||pack.version!==1||!Array.isArray(pack.files))throw 0}catch(e){setStatus('Invalid CookieHost package.','The reconstructed data does not have the expected format.','error');return}const htmlFiles=pack.files.filter(f=>typeof f.path==='string'&&/\.html?$/i.test(f.path));if(!htmlFiles.length){setStatus('The baked website contains no HTML entry point.','Upload at least one .html file.','error');return}const entry=htmlFiles.find(f=>f.path.toLowerCase()==='index.html')||htmlFiles[0];frame.srcdoc=inlineAssets(entry.content,pack.files,entry.path);wrap.hidden=false;setStatus('Step 5 · Website loaded!','Your website is rendered below. It is running inside an isolated frame.','success')}catch(e){setStatus('Unable to load CookieHost data.','Something unexpected happened while reading the cookies.','error')}})();
